# Generated by Django 4.2 on 2026-06-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AksesSimulasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Hak Akses Simulasi',
                'verbose_name_plural': 'Hak Akses Simulasi',
                'permissions': [('can_access_simulasi', 'Dapat Mengakses Simulasi Rebut Kursi')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
