# Generated by Django 4.2 on 2026-06-17 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0005_partai_is_lolos_pt'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekapSuara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suara_tidak_sah', models.IntegerField(default=0)),
                ('kecamatan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rekap_suara_kokab', to='master.kecamatan')),
            ],
            options={
                'verbose_name': 'Rekap Suara',
                'verbose_name_plural': 'Rekap Suara',
            },
        ),
        migrations.CreateModel(
            name='Dapil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, unique=True)),
                ('jumlah_kursi', models.IntegerField()),
                ('kecamatan', models.ManyToManyField(related_name='dapil_kokab_set', to='master.kecamatan')),
                ('kokab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dapil_kokab_set', to='master.kokab')),
            ],
            options={
                'verbose_name': 'Dapil',
                'verbose_name_plural': 'Dapil',
            },
        ),
        migrations.CreateModel(
            name='DetailSuara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_suara', models.IntegerField(default=0)),
                ('partai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_suara_kokab_set', to='master.partai')),
                ('rekap_suara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_suara', to='pileg_kokab.rekapsuara')),
            ],
            options={
                'unique_together': {('rekap_suara', 'partai')},
            },
        ),
    ]
