# Generated by Django 4.2 on 2026-06-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_partai_is_lolos_pt'),
        ('pileg_kokab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekapKursiKokab',
            fields=[
            ],
            options={
                'verbose_name': 'Rekap Kursi per Kota/Kab',
                'verbose_name_plural': 'Rekap Kursi per Kota/Kab',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('master.kokab',),
        ),
    ]
