# Generated by Django 4.2 on 2026-06-17 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kokab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=24, unique=True)),
                ('nama', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Kota/Kabupaten',
                'verbose_name_plural': 'Kota/Kabupaten',
            },
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=24, unique=True)),
                ('nama', models.CharField(max_length=255, unique=True)),
                ('jumlah_penduduk', models.IntegerField()),
                ('dpt_pemilu', models.IntegerField()),
                ('dpt_pilkada', models.IntegerField()),
                ('kokab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.kokab')),
            ],
            options={
                'verbose_name': 'Kecamatan',
                'verbose_name_plural': 'Kecamatan',
            },
        ),
    ]
