# Generated by Django 4.2 on 2026-06-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kecamatan',
            name='nama',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='kecamatan',
            unique_together={('kokab', 'nama')},
        ),
    ]
