# Generated by Django 5.2.15 on 2026-06-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_kecamatan_nama_alter_kecamatan_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('no_urut', models.IntegerField(unique=True)),
                ('warna', models.CharField(max_length=50)),
                ('logo_url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'Partai',
            },
        ),
    ]
