# Generated by Django 5.2.15 on 2026-06-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_partai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partai',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partai',
            name='warna',
            field=models.CharField(default='#808080', help_text='Kode Hex (contoh: #808080)', max_length=50),
        ),
    ]
