# Generated by Django 4.2 on 2026-06-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_partai_logo_url_alter_partai_warna'),
    ]

    operations = [
        migrations.AddField(
            model_name='partai',
            name='is_lolos_pt',
            field=models.BooleanField(default=False, help_text='Centang jika partai ini lolos Ambang Batas Parlemen (Khusus DPR RI)', verbose_name='Lolos PT 4%'),
        ),
    ]
