# Generated by Django 4.2 on 2026-06-18 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0005_partai_is_lolos_pt'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='Browser/Perangkat')),
                ('waktu_login', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Login')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Riwayat Login',
                'verbose_name_plural': 'Riwayat Login',
                'ordering': ['-waktu_login'],
            },
        ),
    ]
