# Generated by Django 4.2 on 2026-06-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0004_alter_partai_logo_url_alter_partai_warna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dapil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255, unique=True)),
                ('jumlah_kursi', models.IntegerField()),
                ('kokab', models.ManyToManyField(to='master.kokab')),
            ],
            options={
                'verbose_name': 'Dapil',
                'verbose_name_plural': 'Dapil',
            },
        ),
    ]
