# Generated by Django 4.2 on 2026-06-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_partai_logo_url_alter_partai_warna'),
        ('pileg_ri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dapil',
            name='kokab',
            field=models.ManyToManyField(blank=True, to='master.kokab'),
        ),
    ]
