# Generated by Django 4.2 on 2026-06-17 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_partai_logo_url_alter_partai_warna'),
        ('pileg_ri', '0002_alter_dapil_kokab'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekapSuara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suara_tidak_sah', models.IntegerField(default=0)),
                ('kecamatan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='master.kecamatan')),
            ],
            options={
                'verbose_name': 'Rekap Suara',
                'verbose_name_plural': 'Rekap Suara',
            },
        ),
        migrations.CreateModel(
            name='DetailSuara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_suara', models.IntegerField(default=0)),
                ('partai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.partai')),
                ('rekap_suara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_suara', to='pileg_ri.rekapsuara')),
            ],
            options={
                'unique_together': {('rekap_suara', 'partai')},
            },
        ),
    ]
